version: '3.6'
services:
  web:
    build:
      context: ./
    # Keep from creating a network
    network_mode: bridge
    ports:
      - "80:9000"
    volumes:
      - ./:/workspace
      - ~/.ssh:/home/node/.ssh
      - ~/.bashrc:/home/node/.bashrc
      - ~/.gitconfig:/home/node/.gitconfig
    working_dir: /workspace
    command: grunt serve
